# -*- coding: utf-8 -*-
"""aircraft.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fln7U3pmZ908itiP-2JgFE8JaR67rVBZ
"""

import warnings

# Ignore all DeprecationWarning messages
warnings.filterwarnings("ignore", category=DeprecationWarning)

import numpy as np
import pandas as pd

np.random.seed(42)
n = 5000

rpm = np.random.randint(500, 3000, n)  # Engine rotational speed

noise_v = np.random.normal(0, 0.8, n)
vibration_rms = 1 + 0.002 * rpm + noise_v   # V=1+0.002*RPM+noise
vibration_rms = np.clip(vibration_rms, 0.5, 12)

noise_t = np.random.normal(0, 3, n)
temperature = 40 + 0.005 * rpm + 2 * vibration_rms + noise_t   # T = 40 + 0.005*RPM + 2V + noise
temperature = np.clip(temperature, 40, 120)

noise_a = np.random.normal(0, 4, n)
acoustic_db = 50 + 3 * vibration_rms + noise_a   # A = 50 + 3V + noise
acoustic_db = np.clip(acoustic_db, 50, 110)

risk = np.where(
    (vibration_rms > 6) |
    (temperature > 90) |
    (acoustic_db > 85),
    1, 0
)  # 0=Normal,1=High Risk


data = pd.DataFrame({
    "vibration_rms": vibration_rms,
    "temperature": temperature,
    "rpm": rpm,
    "acoustic_db": acoustic_db,
    "risk": risk
})
print("Aircraft Vibration Sensor Data :")
print(data.head())

data.to_csv("aircraft_sensor_data.csv", index=False)

"""Loading dataset"""

df_pd = pd.read_csv("aircraft_sensor_data.csv")
print(df_pd.head())

"""EDA (Exploratory Data Analysis )"""

print(df_pd.shape)

print(df_pd.info())

print(df_pd.describe())

print(df_pd["risk"].value_counts())

"""Converting Pandas to Polars"""

import polars as pl

df_polars = pl.from_pandas(data)

print(df_polars.head())

"""Filtering"""

high_risk = df_polars.filter(pl.col("risk") == 1)  # High risk machines
print(high_risk.head())

high_rpm = df_polars.filter(pl.col("rpm") > 2500)  # Machines with high RPM
print(high_rpm.head())

high_vrms = df_polars.filter(pl.col("vibration_rms") > 6) # High vibration machines
print(high_vrms.head())

high_acoustic_db = df_polars.filter(pl.col("acoustic_db") > 85) # High acoustic machines i.e is noisy machines
print(high_acoustic_db.head())

high_rpmAndvibration = df_polars.filter(                #  High RPM + High Vibration
    (pl.col("rpm") > 2000) &
    (pl.col("vibration_rms") > 5)
)
print(high_rpmAndvibration.head())

"""Aggregation"""

agg_pl = df_polars.group_by("risk").mean()
print(agg_pl)

df_polars.group_by("risk").count()

df_polars.select([
    pl.col("rpm").min().alias("min_rpm"),
    pl.col("rpm").max().alias("max_rpm"),
    pl.col("temperature").max().alias("max_temperature"),
    pl.col("vibration_rms").max().alias("max_vibration")
])

"""# Data Validation (Great Expectations)"""

!pip install great_expectations==0.17.23

import great_expectations as gx

!great_expectations init

context = gx.get_context()

suite = context.add_or_update_expectation_suite(
    expectation_suite_name="aircraft_suite"
)

context.sources.add_or_update_pandas(
    name="pandas_datasource"
)

datasource = context.get_datasource("pandas_datasource")

data_asset = datasource.add_dataframe_asset(
    name="aircraft_data"
)

batch_request = data_asset.build_batch_request(
    dataframe=df_pd
)

validator = context.get_validator(
    batch_request=batch_request,
    expectation_suite_name="aircraft_suite"
)

validator.expect_table_row_count_to_be_between(
    min_value=4000,
    max_value=6000
)

validator.expect_column_values_to_not_be_null("rpm")

validator.expect_column_values_to_be_between(
    "temperature",
    min_value=40,
    max_value=120
)

validator.expect_column_values_to_be_between(
    "rpm",
    min_value=500,
    max_value=3000
)

validator.expect_column_values_to_be_in_set(
    "risk",
    value_set=[0, 1]
)

validator.save_expectation_suite()

checkpoint = context.add_or_update_checkpoint(
    name="aircraft_checkpoint",
    validator=validator
)

checkpoint_result = checkpoint.run()

context.build_data_docs()

context.open_data_docs()

docs_sites = context.get_docs_sites_urls()

print(docs_sites)

!zip -r aircraft_validation_report.zip gx/uncommitted/data_docs/

from google.colab import files
files.download("aircraft_validation_report.zip")

"""# Machine Learning"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import shap
import matplotlib.pyplot as plt
!pip install fairlearn
from fairlearn.metrics import MetricFrame, selection_rate, false_positive_rate, false_negative_rate
from IPython.display import IFrame

df = pd.read_csv("aircraft_sensor_data.csv")  # Replace with your file path

#  Add synthetic sensitive attribute if missing

if "machine_type" not in df.columns:
    df["machine_type"] = np.random.choice(["A", "B"], size=df.shape[0])

print("Dataset preview:")
display(df.head())
print("\nColumns:", df.columns)

features = ["rpm", "vibration_rms", "temperature", "acoustic_db", "machine_type"]
target = "risk"

X = df[features]
y = df[target]

X = pd.get_dummies(X, columns=["machine_type"], drop_first=True)  # creates machine_type_B

# Train-test split (80-20)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 8️⃣ Random Forest Training
# =========================
rf = RandomForestClassifier(n_estimators=150, random_state=42)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

print("\n=== Random Forest Evaluation ===")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# 🔟 Feature Importance (creative visualization)
# =========================
importances = rf.feature_importances_
feat_names = X_train.columns

plt.figure(figsize=(8,5))
bars = plt.barh(feat_names, importances, color=plt.cm.viridis(importances))
plt.title("🎯 Random Forest Feature Importance", fontsize=16)
plt.xlabel("Importance", fontsize=12)
plt.ylabel("Features", fontsize=12)

# Add value labels
for bar in bars:
    width = bar.get_width()
    plt.text(width + 0.005, bar.get_y() + bar.get_height()/2, f"{width:.2f}", va='center')
plt.show()

# 1️⃣1️⃣ SHAP Explanations
# =========================
explainer = shap.TreeExplainer(rf)
shap_values = explainer(X_test)

# Summary plot (beeswarm)
shap.summary_plot(shap_values, X_test, plot_type="dot", show=True)

# Summary bar plot
shap.summary_plot(shap_values, X_test, plot_type="bar", show=True)

# 1️⃣2️⃣ Bias / Fairness Analysis
# =========================
sensitive_feature = X_test["machine_type_B"]

metrics = {
    "accuracy": lambda y_true, y_pred: (y_true == y_pred).mean(),
    "selection_rate": selection_rate,
    "false_positive_rate": false_positive_rate,
    "false_negative_rate": false_negative_rate
}

mf = MetricFrame(metrics=metrics,
                 y_true=y_test,
                 y_pred=y_pred,
                 sensitive_features=sensitive_feature)

print("\n=== Bias / Fairness Analysis by Machine Type ===")
display(mf.by_group)